### ISSUE TITLE
{spark,hadoop}-bam sync-up

### ISSUE THREAD

**Issue by ryan-williams** [hammerlab/spark-bam#16]
@tomwhite and I are going to chat about these projects tomorrow at 11am ET in case anyone wants to join (@lbergelson @heuermh @fnothaft), [this hangout link should work](https://hangouts.google.com/hangouts/_/calendar/cnlhbi5ibGFrZS53aWxsaWFtc0BnbWFpbC5jb20.6ksjgphn70qm8bb1c4rj6b9kcosmabb2ccqj6bb26gr66eb168sjaphicg?authuser=0)

**Comment by heuermh** [comment]
Sounds good, I should be able to make it.

**Comment by ryan-williams** [comment]
A few notes:

- Tom has prototyped some of the spark-bam features in hadoop-bam, including direct construction of RDDs instead of using Hadoop filesystem APIs, with parallel-split-computation
- If hadoop-bam had those features that would be great and spark-bam would not need to keep being maintained / used
- Tom thinks he has cycles to take that over the finish line
- I will try to do a spark-bam documentation/benchmark refresh showing how to run against [large public datasets on Google Cloud](http://googlegenomics.readthedocs.io/en/latest/use_cases/discover_public_data/1000_genomes.html#google-cloud-platform-data-locations); we can use those for easier speed+accuracy comparisons going forward
- Tom tried to use a caching/buffering abstraction in htsjdk to mimic the CachingChannel in spark-bam (working around google-cloud-nio [throwing away buffered data](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.38.0/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java#L104) [on any rewind](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/v0.38.0/google-cloud-contrib/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/CloudStorageReadChannel.java#L164)), but the former was slower than the latter for some reason (still way faster than an uncached version, I'd guess?)
- Some hadoop-bam identity-confusion on the horizon as it starts to include Spark APIs; also usual governance open questions

**Comment by ryan-williams** [comment]
Filed https://github.com/GoogleCloudPlatform/google-cloud-java/issues/3041 about the buffering issue, fwiw

**Comment by heuermh** [comment]
A few additional thoughts:
* Developing integration tests that run off a subset of the benchmark data on AWS and Google Cloud would be useful, if only at release time
* Adding a Spark dependency to Hadoop-BAM brings with it some complexity with multiple Spark and Scala versions.  We've recently dropped Spark 1.x and are Spark 2.x Scala 2.10 and 2.11 only, but of course Spark 3 and Scala 2.12 aren't far off.
* If we need project governance around new work, since Apache Incubator won't be an option, we'd be willing to add new repositories, CLA, CI, etc. under the [Big Data Genomics organization](https://github.com/bigdatagenomics)

**Comment by lbergelson** [comment]
Sorry I couldn't make it.  It sounds like there was good progress working through some things though.  Thank you to all the people who did make it.

**Comment by tomwhite** [comment]
Thanks for the meeting @ryan-williams and @heuermh.

I've opened an issue to discuss my prototype here: https://github.com/HadoopGenomics/Hadoop-BAM/issues/196

> Tom tried to use a caching/buffering abstraction in htsjdk to mimic the CachingChannel in spark-bam (working around google-cloud-nio throwing away buffered data on any rewind), but the former was slower than the latter for some reason (still way faster than an uncached version, I'd guess?)

Yes, that's right. I didn't dig into the perf difference between htsjdk's SeekableBufferedStream and CachingChannel (perhaps its a Java old IO vs NIO difference - something that's fixable), but both are way faster than not caching at all.

**Comment by tomwhite** [comment]
> If we need project governance around new work, since Apache Incubator won't be an option, we'd be willing to add new repositories, CLA, CI, etc. under the Big Data Genomics organization

Interesting idea and thanks for the offer @heuermh. Would a BSD/MIT license be OK?

**Comment by heuermh** [comment]
> Would a BSD/MIT license be OK?

I don't see why not, I will confirm.

**Comment by fnothaft** [comment]
Hi all, I'd have loved to be involved in this call. Please invite me to any future calls, if possible. Thanks!

**Comment by tomwhite** [comment]
@fnothaft definitely. It might be useful to have another call soon to discuss the governance options further. I'd be happy to organise one if there's interest.

**Comment by fnothaft** [comment]
Yes, it would probably make sense for us to have a standing call (biweekly/monthly?)
